### ISSUE TITLE
TypeError: encode() missing 1 required positional argument: 'texts'

### ISSUE THREAD

**Issue by IS5882** [amansrivastava17/embedding-as-service#19]
hello, I always get this error

TypeError: encode() missing 1 required positional argument: 'texts'
on this line:
vecs = en.encode(texts=['hello aman', 'how are you?'])  

I don't understand why even though texts isn't missing ?

**Comment by amansrivastava17** [comment]
@IS5882 Hi, First of all thank you for raising the issue, here we got the issue and fixed it in the latest release `1.0.0`

just upgrade the current package following below command
`pip install embedding-as-service==1.0.0`

Hope this will resolve the issue.

Thanks Again
