### ISSUE TITLE
Will be great if we can specify where and how to store embedding weights

### ISSUE THREAD

**Issue by tlunati** [amansrivastava17/embedding-as-service#27]
A little bit more flexibility regarding where to store embeddings weights will be greatly appreciated in order to share / reuse weights already downloaded (sorry I don't have enough time to write the code right now)

from embedding_as_service.text.encode import Encoder
en = Encoder(embedding='bert', model='bert_base_cased', model_path = '/what/ever/I/want', download=False)

Really a great piece of work, I'm playing with it since 2 hours, works like a charm
Thx

**Comment by amansrivastava17** [comment]
@tlunati Hi Tlunati,  feeling great that you liked it.
Actually you don't need to pass download param every time, for a given machine, you have to pass it for the first time, which in turn download the model on system. 

so next time when you initiate instance just call 
```en = Encoder(embedding='bert', model='bert_base_cased')```

Also after getting your feedback, we are thinking to remove it as param as it might confuse users.

Once again, thank you for your valuable feedback.

**Comment by tlunati** [comment]
Yes, but when you are using google colab, you need to reload the weights each time. Even if it is speed (20s) ... quite annoying

**Comment by ashutoshsingh0223** [comment]
We will surely take it up.

**Comment by ashutoshsingh0223** [comment]
We have made the encoder class Singleton. If you initialize the class with  the same arguments, it will be loaded from memory making the loading of weights faster.
