### ISSUE TITLE
issue during installation

### ISSUE THREAD

**Issue by sunyilgdx** [amansrivastava17/embedding-as-service#36]
When I use this
 `pip install embedding-as-service` 
or 
`python setup.py`

Issue : 
`Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    long_description = fh.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 169: illegal multibyte sequence`

Installation environment
`Windows10+Python36`

**Comment by amansrivastava17** [comment]
@sunyilgdx Can you try it once more. follow the below command.

`pip install embedding-as-service==1.3.0`
