### ISSUE TITLE
Does embedding as service support word embedding?

### ISSUE THREAD

**Issue by Ailing-Zou** [amansrivastava17/embedding-as-service#40]
You mention about sentence embedding, so does embedding as service support word embedding?

**Comment by ashutoshsingh0223** [comment]
Yes. There are distributed vector models like GLoVe and FastText. In addition to these you can take token level vectors from models like BERT by passing `pooling=None` in the `encode` method.

**Comment by Ailing-Zou** [comment]
Ok, thanks so much!
