### ISSUE TITLE
Performance issue in the difinition of get_cache_fn, server/embedding_as_service/text/xlnet/models/train.py(P1)

### ISSUE THREAD

**Issue by DLPerf** [amansrivastava17/embedding-as-service#66]
Hello, I found a performance issue in the definition of `get_cache_fn`, server/embedding_as_service/text/xlnet/models/train.py, [`tf.zeros`](https://github.com/amansrivastava17/embedding-as-service/blob/7c0d8df576f7c01c28a78d4e4c08d303bdcb78d2/server/embedding_as_service/text/xlnet/models/train.py#L208) will be created repeatedly during program execution, resulting in reduced efficiency. I think it should be created before the loop in `cache_fn`.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by amansrivastava17** [comment]
Hi DLperf, 
Thank you for pointing the issue, will be glad if you can create a PR. Will be happy to review.
